#!/usr/bin/env python3
"""
Pre-render the latest Journal posts into the static HTML.

The Journal page shows a carousel that assets/js/journal-carousel.js fills at
runtime from /api/journal (worker/journal.js, which proxies the TravelPixieFreak
category feeds). Crawlers that do not run JavaScript, including most AI
crawlers, never saw those posts, only the static "First stories coming soon"
panel. This script fetches the same two feeds and writes the posts into the
page as the static fallback block, in the same card markup the carousel uses:

  - visitors with JavaScript see no difference (the script hides this block as
    soon as the carousel loads, exactly as it hid the old "coming soon" panel);
  - crawlers, no-JS visitors and visitors whose /api/journal request fails see
    the real latest posts (title, date, excerpt, link) and a link to the archive.

Then it refreshes the JSON-LD (scripts/generate-structured-data.py), which lists
the same posts, and bumps the sitemap <lastmod> of the pages that changed.

Safety: it never replaces a populated block with an empty one. If a feed cannot
be fetched or has no valid items, that language is left untouched (a warning is
printed, the exit code stays 0). Feed text is untrusted: every value is
HTML-escaped, and only links under https://travelpixiefreak.com/ are accepted.

Usage:  python3 scripts/sync-journal.py
Run daily by .github/workflows/journal-sync.yml. Stdlib only.
"""
from __future__ import annotations

import datetime
import email.utils
import html
import re
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Same sources as worker/journal.js (one WordPress category per language).
FEEDS = {
    "en": "https://travelpixiefreak.com/category/shades-of-human-life/feed/",
    "pl": "https://travelpixiefreak.com/category/odcienie-ludzkiego-zycia/feed/",
}
ARCHIVES = {
    "en": "https://travelpixiefreak.com/category/shades-of-human-life/",
    "pl": "https://travelpixiefreak.com/category/odcienie-ludzkiego-zycia/",
}
PAGES = {"en": "journal/index.html", "pl": "pl/journal/index.html"}
BLOG_PREFIX = "https://travelpixiefreak.com/"
MAX_ITEMS = 10  # the feeds' native size, and what the carousel shows
EXCERPT_CHARS = 140  # same cut as truncate() in assets/js/journal-carousel.js
USER_AGENT = "CUDExperienceJournalSync/1.0 (+https://cudexperience.com)"

STRINGS = {
    "en": {"read": "Read on TravelPixieFreak", "all": "All stories on TravelPixieFreak"},
    "pl": {"read": "Czytaj na TravelPixieFreak", "all": "Wszystkie historie na TravelPixieFreak"},
}
PL_MONTHS = ["stycznia", "lutego", "marca", "kwietnia", "maja", "czerwca", "lipca", "sierpnia",
             "września", "października", "listopada", "grudnia"]
EN_MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September",
             "October", "November", "December"]

START = "<!-- journal-feed:start (generated by scripts/sync-journal.py, do not edit by hand) -->"
END = "<!-- journal-feed:end -->"
LEGACY_OPEN = '<div class="cud-lock cud-reveal cud-reveal-3" data-journal-fallback>'


def fetch(url: str) -> str | None:
    for attempt in range(3):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=30) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except Exception as exc:  # network errors, HTTP errors, bad encodings
            print(f"  fetch attempt {attempt + 1} failed for {url}: {exc}")
            time.sleep(2 * (attempt + 1))
    return None


def tag_value(block: str, tag: str) -> str:
    """Mirror tagValue() in worker/journal.js: strip CDATA, drop tags, decode entities."""
    m = re.search(rf"<{tag}[^>]*>([\s\S]*?)</{tag}>", block)
    if not m:
        return ""
    value = m.group(1).strip()
    cdata = re.match(r"^<!\[CDATA\[([\s\S]*)\]\]>$", value)
    if cdata:
        value = cdata.group(1)
    value = re.sub(r"<[^>]+>", "", value)
    return html.unescape(value).strip()


def parse_items(xml: str) -> list[dict]:
    items = []
    for block in re.findall(r"<item>([\s\S]*?)</item>", xml):
        title = tag_value(block, "title")
        link = tag_value(block, "link")
        pub = tag_value(block, "pubDate")
        excerpt = tag_value(block, "description")
        if not (title and link and link.startswith(BLOG_PREFIX)):
            continue
        try:
            date = email.utils.parsedate_to_datetime(pub).astimezone(datetime.timezone.utc).date()
        except (TypeError, ValueError):
            date = None
        items.append({"title": title, "link": link, "date": date, "excerpt": excerpt})
        if len(items) == MAX_ITEMS:
            break
    return items


def truncate(text: str, n: int = EXCERPT_CHARS) -> str:
    text = text.strip()
    if len(text) <= n:
        return text
    cut = text[:n]
    last = cut.rfind(" ")
    return (cut[:last] if last > 40 else cut) + "…"


def fmt_date(date: datetime.date, lang: str) -> str:
    if lang == "pl":
        return f"{date.day} {PL_MONTHS[date.month - 1]} {date.year}"
    return f"{EN_MONTHS[date.month - 1]} {date.day}, {date.year}"


def esc(text: str) -> str:
    """HTML-escape and write non-ASCII as numeric references, like the rest of the site."""
    return html.escape(text, quote=True).encode("ascii", "xmlcharrefreplace").decode("ascii")


def render_card(item: dict, lang: str) -> str:
    when = ""
    if item["date"]:
        when = f'<time datetime="{item["date"].isoformat()}">{esc(fmt_date(item["date"], lang))}</time>'
    return (
        f'<a class="cud-jrl-card" href="{esc(item["link"])}" target="_blank" rel="noopener">'
        f'<span class="cud-jrl-card-in"><span class="cud-jrl-date">{when}</span>'
        f'<span class="cud-jrl-h">{esc(" ".join(item["title"].split()))}</span>'
        f'<span class="cud-jrl-ex">{esc(" ".join(truncate(item["excerpt"]).split()))}</span>'
        f'<span class="cud-jrl-link">{esc(STRINGS[lang]["read"])} &rarr;</span></span></a>'
    )


def render_block(items: list[dict], lang: str) -> str:
    cards = "\n".join(render_card(i, lang) for i in items)
    return (
        f"{START}\n"
        '<div class="cud-jrl cud-reveal cud-reveal-3" data-journal-fallback>\n'
        f'<div class="cud-jrl-viewport"><div class="cud-jrl-track">\n{cards}\n</div></div>\n'
        f'<p class="cud-p cud-xh-more"><a class="cud-pv-link" href="{esc(ARCHIVES[lang])}" '
        f'target="_blank" rel="noopener">{esc(STRINGS[lang]["all"])} &rarr;</a></p>\n'
        "</div>\n"
        f"{END}"
    )


def div_end(text: str, start: int) -> int:
    """Index just past the </div> that closes the <div> opening at `start`."""
    depth = 0
    for m in re.finditer(r"<div\b|</div>", text[start:]):
        depth += -1 if m.group(0).startswith("</") else 1
        if depth == 0:
            return start + m.end()
    raise SystemExit("unbalanced <div> in journal page")


def apply_block(text: str, block: str) -> str:
    if START in text:
        a = text.index(START)
        b = text.index(END, a) + len(END)
        return text[:a] + block + text[b:]
    a = text.find(LEGACY_OPEN)
    if a < 0:
        raise SystemExit("journal page has neither the generated block nor the original fallback panel")
    return text[:a] + block + text[div_end(text, a):]


def bump_lastmod(path_rel: str, today: str) -> None:
    sitemap = ROOT / "sitemap.xml"
    loc = "https://cudexperience.com/" + path_rel[: -len("index.html")]
    s = sitemap.read_text(encoding="utf-8")
    new = re.sub(rf"(<url><loc>{re.escape(loc)}</loc><lastmod>)[^<]+(</lastmod>)", rf"\g<1>{today}\g<2>", s)
    if new != s:
        sitemap.write_text(new, encoding="utf-8")


def main() -> int:
    today = datetime.datetime.now(datetime.timezone.utc).date().isoformat()
    changed = []
    for lang, feed_url in FEEDS.items():
        rel = PAGES[lang]
        print(f"[{lang}] {feed_url}")
        xml = fetch(feed_url)
        items = parse_items(xml) if xml else []
        if not items:
            print(f"::warning::No usable posts from the {lang} Journal feed; {rel} left unchanged")
            continue
        path = ROOT / rel
        text = path.read_text(encoding="utf-8")
        new = apply_block(text, render_block(items, lang))
        if new == text:
            print(f"  {len(items)} posts, {rel} already up to date")
            continue
        path.write_text(new, encoding="utf-8")
        bump_lastmod(rel, today)
        changed.append(rel)
        print(f"  {len(items)} posts written to {rel}")

    if changed:
        # JSON-LD lists the same posts; regenerate it (and the CSP hash).
        subprocess.run([sys.executable, str(ROOT / "scripts" / "generate-structured-data.py")], check=True)
    print("Changed: " + (", ".join(changed) if changed else "nothing"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
